version: '3.3'
services:
    frontend:
        build: "./frontend"
        ports:
            - "8501:8501"
        environment:
            - BACKEND_ADDR=nginx:80
        restart: "always"
        networks:
            - "mandelbrot.network"
    backend:
        build: "./backend"
        ports:
            - "5000"
        environment:
            - GOPORT=5000
        restart: "always"
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: '1.0'
        networks: 
            - "mandelbrot.network"
    nginx:
        build: "./nginx"
        depends_on:
            - backend
        ports: 
            - "80:80"
        networks: 
            - "mandelbrot.network"
networks: 
    mandelbrot.network: