
version: '3.3'

#services describe the containers that will start
services: 
    # backend is the container name for our Go backend
    frontend:
        # build: "./frontend/"
        image: andreaventura/ecam:mandelbrot_frontend
        ports:
            - "8501:8501"
        restart: "always"
        networks: 
            - "mandelbrot.network"
    backend:
        # build: "./backend/main"
        image: andreaventura/ecam:mandelbrot_backend
        # Exposes the port 5000 from a container and binds it to a random port
        ports:
            - "5000:5000"
        # If the container goes down, it will restart
        restart: "always"
        # Connects the backend to a common mandelbrot.network bridge
        networks: 
            - "mandelbrot.network"
        # cpuset: "0-5"
        # Starts up 6 replicas of the same image
        # deploy:
        #     replicas: 6
            # resources:
            #     limits:
            #         cpus: '1.0'
    # nginx container
    nginx:
        # specifies the latest nginx image
        # build: "./backend/nginx"
        image: andreaventura/ecam:mandelbrot_nginx
        # Connects the conf file of the container to the conf file in our folder
        # volumes:
        #     - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        # It will start up the nginx only when all backend containers have started
        depends_on: 
            - backend
        # Connects the port 80 of the nginx container to localhost:80 or localhost
        ports: 
            - "80:80"
        networks: 
            - "mandelbrot.network"
networks: 
    mandelbrot.network: